// ReSharper disable InconsistentNaming
namespace HostApi;

using Internal.DotNet;

/// <summary>
/// Runs a dotnet application.
/// </summary>
/// <param name="Args">Specifies the set of command line arguments to use when starting the tool.</param>
/// <param name="Vars">Specifies the set of environment variables that apply to this process and its child processes.</param>
/// <param name="AdditionalProbingPaths">Paths containing probing policy and assemblies to probe.</param>
/// <param name="ExecutablePath">Overrides the tool executable path.</param>
/// <param name="WorkingDirectory">Specifies the working directory for the tool to be started.</param>
/// <param name="PathToApplication">Specifies the path to an application .dll file to run the application. To run the application means to find and execute the entry point, which in the case of console apps is the Main method. For example, dotnet myapp. dll runs the myapp application.</param>
/// <param name="AdditionalDeps">Path to an additional .deps.json file. A deps.json file contains a list of dependencies, compilation dependencies, and version information used to address assembly conflicts.</param>
/// <param name="FxVersion">Version of the .NET runtime to use to run the application.</param>
/// <param name="RollForward">Controls how roll forward is applied to the app. The SETTING can be one of the following values. If not specified, <see cref="HostApi.RollForward.Minor"/> is the default.</param>
/// <param name="Diagnostics">Enables diagnostic output.</param>
/// <param name="ShortName">Specifies a short name for this operation.</param>
[Target]
public partial record DotNet(
    IEnumerable<string> Args,
    IEnumerable<(string name, string value)> Vars,
    IEnumerable<string> AdditionalProbingPaths,
    string PathToApplication = "",
    string AdditionalDeps = "",
    string FxVersion = "",
    RollForward? RollForward = default,
    bool? Diagnostics = default,
    string ExecutablePath = "",
    string WorkingDirectory = "",
    string ShortName = "")
{
    /// <summary>
    /// Create a new instance of the command.
    /// </summary>
    /// <param name="args">Specifies the set of command line arguments to use when starting the tool.</param>
    public DotNet(params string[] args)
        : this(args, [], [])
    {
    }

    /// <summary>
    /// Create a new instance of the command.
    /// </summary>
    public DotNet()
        : this([], [], [])
    {
    }

    /// <inheritdoc/>
    public IStartInfo GetStartInfo(IHost host)
    {
        if (host == null) throw new ArgumentNullException(nameof(host));
        return host.CreateCommandLine(ExecutablePath)
            .WithShortName(ToString())
            .WithWorkingDirectory(WorkingDirectory)
            .WithVars(Vars.ToArray())
            .AddNotEmptyArgs(PathToApplication)
            .AddArgs(AdditionalProbingPaths.ToArgs("--additionalprobingpath"))
            .AddArgs(AdditionalDeps.ToArgs("--additional-deps"))
            .AddArgs(FxVersion.ToArgs("--fx-version"))
            .AddArgs(RollForward.ToArgs("--roll-forward"))
            .AddBooleanArgs(
                ("--diagnostics", Diagnostics)
            )
            .AddArgs(Args.ToArray());
    }

    /// <inheritdoc/>
    public override string ToString() => "".GetShortName(ShortName, PathToApplication);
}

/// <summary>
/// Executes a dotnet application.
/// </summary>
/// <param name="Args">Specifies the set of command line arguments to use when starting the tool.</param>
/// <param name="Vars">Specifies the set of environment variables that apply to this process and its child processes.</param>
/// <param name="AdditionalProbingPaths">Paths containing probing policy and assemblies to probe.</param>
/// <param name="ExecutablePath">Overrides the tool executable path.</param>
/// <param name="WorkingDirectory">Specifies the working directory for the tool to be started.</param>
/// <param name="PathToApplication">Specifies the path to an application .dll file to run the application. To run the application means to find and execute the entry point, which in the case of console apps is the Main method. For example, dotnet myapp. dll runs the myapp application.</param>
/// <param name="DepsFile">Path to a deps.json file. A deps.json file is a configuration file that contains information about dependencies necessary to run the application. This file is generated by the .NET SDK.</param>
/// <param name="AdditionalDeps">Path to an additional .deps.json file. A deps.json file contains a list of dependencies, compilation dependencies, and version information used to address assembly conflicts.</param>
/// <param name="FxVersion">Version of the .NET runtime to use to run the application.</param>
/// <param name="RollForward">Controls how roll forward is applied to the app. The SETTING can be one of the following values. If not specified, <see cref="HostApi.RollForward.Minor"/> is the default.</param>
/// <param name="RuntimeConfig">Path to a runtimeconfig.json file. A runtimeconfig.json file contains run-time settings and is typically named &lt;applicationname&gt;.runtimeconfig.json.</param>
/// <param name="Diagnostics">Enables diagnostic output.</param>
/// <param name="ShortName">Specifies a short name for this operation.</param>
[Target]
public partial record DotNetExec(
    IEnumerable<string> Args,
    IEnumerable<(string name, string value)> Vars,
    IEnumerable<string> AdditionalProbingPaths,
    string PathToApplication = "",
    string DepsFile = "",
    string AdditionalDeps = "",
    string FxVersion = "",
    RollForward? RollForward = default,
    string RuntimeConfig = "",
    bool? Diagnostics = default,
    string ExecutablePath = "",
    string WorkingDirectory = "",
    string ShortName = "")
{
    /// <summary>
    /// Create a new instance of the command.
    /// </summary>
    /// <param name="args">Specifies the set of command line arguments to use when starting the tool.</param>
    public DotNetExec(params string[] args)
        : this(args, [], [])
    {
    }

    /// <summary>
    /// Create a new instance of the command.
    /// </summary>
    public DotNetExec()
        : this([], [], [])
    {
    }

    /// <inheritdoc/>
    public IStartInfo GetStartInfo(IHost host)
    {
        if (host == null) throw new ArgumentNullException(nameof(host));
        return host.CreateCommandLine(ExecutablePath)
            .WithShortName(ToString())
            .WithWorkingDirectory(WorkingDirectory)
            .WithVars(Vars.ToArray())
            .AddArgs("exec")
            .AddNotEmptyArgs(PathToApplication)
            .AddArgs(AdditionalProbingPaths.ToArgs("--additionalprobingpath"))
            .AddArgs(DepsFile.ToArgs("--depsfile"))
            .AddArgs(AdditionalDeps.ToArgs("--additional-deps"))
            .AddArgs(FxVersion.ToArgs("--fx-version"))
            .AddArgs(RollForward.ToArgs("--roll-forward"))
            .AddArgs(RuntimeConfig.ToArgs("--runtimeconfig"))
            .AddBooleanArgs(
                ("--diagnostics", Diagnostics)
            )
            .AddArgs(Args.ToArray());
    }

    /// <inheritdoc/>
    public override string ToString() => "".GetShortName(ShortName, "exec", PathToApplication);
}

/// <summary>
/// Adds or updates a package reference in a project file.
/// </summary>
/// <param name="Args">Specifies the set of command line arguments to use when starting the tool.</param>
/// <param name="Vars">Specifies the set of environment variables that apply to this process and its child processes.</param>
/// <param name="Sources">The URI of the NuGet package source to use during the restore operation.</param>
/// <param name="ExecutablePath">Overrides the tool executable path.</param>
/// <param name="WorkingDirectory">Specifies the working directory for the tool to be started.</param>
/// <param name="Project">The project or solution file to operate on. If not specified, the command searches the current directory for one. If more than one solution or project is found, an error is thrown.</param>
/// <param name="PackageName">The package reference to add.</param>
/// <param name="Framework">Adds a package reference only when targeting a specific framework.</param>
/// <param name="NoRestore">Adds a package reference without performing a restore preview and compatibility check.</param>
/// <param name="PackageDirectory">The directory where to restore the packages. The default package restore location is %userprofile%\.nuget\packages on Windows and ~/.nuget/packages on macOS and Linux.</param>
/// <param name="Prerelease">Allows prerelease packages to be installed. Available since .NET Core 5 SDK.</param>
/// <param name="Version">Version of the package</param>
/// <param name="Diagnostics">Enables diagnostic output.</param>
/// <param name="ShortName">Specifies a short name for this operation.</param>
[Target]
public partial record DotNetAddPackage(
    IEnumerable<string> Args,
    IEnumerable<(string name, string value)> Vars,
    IEnumerable<string> Sources,
    string Project = "",
    string PackageName = "",
    string Framework = "",
    bool? NoRestore = default,
    string PackageDirectory = "",
    bool? Prerelease = default,
    string Version = "",
    bool? Diagnostics = default,
    string ExecutablePath = "",
    string WorkingDirectory = "",
    string ShortName = "")
{
    /// <summary>
    /// Create a new instance of the command.
    /// </summary>
    /// <param name="args">Specifies the set of command line arguments to use when starting the tool.</param>
    public DotNetAddPackage(params string[] args)
        : this(args, [], [])
    {
    }

    /// <summary>
    /// Create a new instance of the command.
    /// </summary>
    public DotNetAddPackage()
        : this([], [], [])
    {
    }

    /// <inheritdoc/>
    public IStartInfo GetStartInfo(IHost host)
    {
        if (host == null) throw new ArgumentNullException(nameof(host));
        return host.CreateCommandLine(ExecutablePath)
            .WithShortName(ToString())
            .WithWorkingDirectory(WorkingDirectory)
            .WithVars(Vars.ToArray())
            .AddArgs("add")
            .AddNotEmptyArgs(Project)
            .AddArgs("package")
            .AddNotEmptyArgs(PackageName)
            .AddArgs(Sources.ToArgs("--source"))
            .AddArgs(Framework.ToArgs("--framework"))
            .AddArgs(PackageDirectory.ToArgs("--package-directory"))
            .AddArgs(Version.ToArgs("--version"))
            .AddBooleanArgs(
                ("--no-restore", NoRestore),
                ("--prerelease", Prerelease),
                ("--diagnostics", Diagnostics)
            )
            .AddArgs(Args.ToArray());
    }

    /// <inheritdoc/>
    public override string ToString() => "".GetShortName(ShortName, "add", Project, "package", PackageName);
}

/// <summary>
/// Lists the package references for a project or solution.
/// </summary>
/// <param name="Args">Specifies the set of command line arguments to use when starting the tool.</param>
/// <param name="Vars">Specifies the set of environment variables that apply to this process and its child processes.</param>
/// <param name="Frameworks">Displays only the packages applicable for the specified target framework.</param>
/// <param name="Sources">The NuGet sources to use when searching for newer packages. Requires the --outdated or --deprecated option.</param>
/// <param name="ExecutablePath">Overrides the tool executable path.</param>
/// <param name="WorkingDirectory">Specifies the working directory for the tool to be started.</param>
/// <param name="Project">The project or solution file to operate on. If not specified, the command searches the current directory for one. If more than one solution or project is found, an error is thrown.</param>
/// <param name="Config">The NuGet sources to use when searching for newer packages. Requires the --outdated option.</param>
/// <param name="Deprecated">Displays packages that have been deprecated.</param>
/// <param name="HighestMinor">Considers only the packages with a matching major version number when searching for newer packages. Requires the --outdated or --deprecated option.</param>
/// <param name="HighestPatch">Considers only the packages with a matching major and minor version numbers when searching for newer packages. Requires the --outdated or --deprecated option.</param>
/// <param name="IncludePrerelease">Considers packages with prerelease versions when searching for newer packages. Requires the --outdated or --deprecated option.</param>
/// <param name="IncludeTransitive">Lists transitive packages, in addition to the top-level packages. When specifying this option, you get a list of packages that the top-level packages depend on.</param>
/// <param name="Outdated">Lists packages that have newer versions available.</param>
/// <param name="Verbosity">Sets the verbosity level of the command. Allowed values are <see cref="DotNetVerbosity.Quiet"/>, <see cref="DotNetVerbosity.Minimal"/>, <see cref="DotNetVerbosity.Normal"/>, <see cref="DotNetVerbosity.Detailed"/>, and <see cref="DotNetVerbosity.Diagnostic"/>. The default is <see cref="DotNetVerbosity.Minimal"/>. For more information, see <see cref="DotNetVerbosity"/>.</param>
/// <param name="Diagnostics">Enables diagnostic output.</param>
/// <param name="ShortName">Specifies a short name for this operation.</param>
[Target]
public partial record DotNetListPackage(
    IEnumerable<string> Args,
    IEnumerable<(string name, string value)> Vars,
    IEnumerable<string> Frameworks,
    IEnumerable<string> Sources,
    string Project = "",
    string Config = "",
    bool? Deprecated = default,
    bool? HighestMinor = default,
    bool? HighestPatch = default,
    bool? IncludePrerelease = default,
    bool? IncludeTransitive = default,
    bool? Outdated = default,
    DotNetVerbosity? Verbosity = default,
    bool? Diagnostics = default,
    string ExecutablePath = "",
    string WorkingDirectory = "",
    string ShortName = "")
{
    /// <summary>
    /// Create a new instance of the command.
    /// </summary>
    /// <param name="args">Specifies the set of command line arguments to use when starting the tool.</param>
    public DotNetListPackage(params string[] args)
        : this(args, [], [], [])
    {
    }

    /// <summary>
    /// Create a new instance of the command.
    /// </summary>
    public DotNetListPackage()
        : this([], [], [], [])
    {
    }

    /// <inheritdoc/>
    public IStartInfo GetStartInfo(IHost host)
    {
        if (host == null) throw new ArgumentNullException(nameof(host));
        return host.CreateCommandLine(ExecutablePath)
            .WithShortName(ToString())
            .WithWorkingDirectory(WorkingDirectory)
            .WithVars(Vars.ToArray())
            .AddArgs("list")
            .AddNotEmptyArgs(Project)
            .AddArgs("package")
            .AddArgs(Frameworks.ToArgs("--framework"))
            .AddArgs(Sources.ToArgs("--source"))
            .AddArgs(Config.ToArgs("--config"))
            .AddArgs(Verbosity.ToArgs("--verbosity"))
            .AddBooleanArgs(
                ("--deprecated", Deprecated),
                ("--highest-minor", HighestMinor),
                ("--highest-patch", HighestPatch),
                ("--include-prerelease", IncludePrerelease),
                ("--include-transitive", IncludeTransitive),
                ("--outdated", Outdated),
                ("--diagnostics", Diagnostics)
            )
            .AddArgs(Args.ToArray());
    }

    /// <inheritdoc/>
    public override string ToString() => "".GetShortName(ShortName, "list", Project, "package");
}

/// <summary>
/// Removes package reference from a project file.
/// </summary>
/// <param name="Args">Specifies the set of command line arguments to use when starting the tool.</param>
/// <param name="Vars">Specifies the set of environment variables that apply to this process and its child processes.</param>
/// <param name="ExecutablePath">Overrides the tool executable path.</param>
/// <param name="WorkingDirectory">Specifies the working directory for the tool to be started.</param>
/// <param name="Project">The project or solution file to operate on. If not specified, the command searches the current directory for one. If more than one solution or project is found, an error is thrown.</param>
/// <param name="PackageName">The package reference to add.</param>
/// <param name="Diagnostics">Enables diagnostic output.</param>
/// <param name="ShortName">Specifies a short name for this operation.</param>
[Target]
public partial record DotNetRemovePackage(
    IEnumerable<string> Args,
    IEnumerable<(string name, string value)> Vars,
    string Project = "",
    string PackageName = "",
    bool? Diagnostics = default,
    string ExecutablePath = "",
    string WorkingDirectory = "",
    string ShortName = "")
{
    /// <summary>
    /// Create a new instance of the command.
    /// </summary>
    /// <param name="args">Specifies the set of command line arguments to use when starting the tool.</param>
    public DotNetRemovePackage(params string[] args)
        : this(args, [])
    {
    }

    /// <summary>
    /// Create a new instance of the command.
    /// </summary>
    public DotNetRemovePackage()
        : this([], [])
    {
    }

    /// <inheritdoc/>
    public IStartInfo GetStartInfo(IHost host)
    {
        if (host == null) throw new ArgumentNullException(nameof(host));
        return host.CreateCommandLine(ExecutablePath)
            .WithShortName(ToString())
            .WithWorkingDirectory(WorkingDirectory)
            .WithVars(Vars.ToArray())
            .AddArgs("remove")
            .AddNotEmptyArgs(Project)
            .AddArgs("package")
            .AddNotEmptyArgs(PackageName)
            .AddBooleanArgs(
                ("--diagnostics", Diagnostics)
            )
            .AddArgs(Args.ToArray());
    }

    /// <inheritdoc/>
    public override string ToString() => "".GetShortName(ShortName, "remove", Project, "package", PackageName);
}

/// <summary>
/// Adds project-to-project (P2P) references.
/// </summary>
/// <param name="Args">Specifies the set of command line arguments to use when starting the tool.</param>
/// <param name="Vars">Specifies the set of environment variables that apply to this process and its child processes.</param>
/// <param name="References">Project-to-project (P2P) references to add. Specify one or more projects. Glob patterns are supported on Unix/Linux-based systems.</param>
/// <param name="ExecutablePath">Overrides the tool executable path.</param>
/// <param name="WorkingDirectory">Specifies the working directory for the tool to be started.</param>
/// <param name="Project">The project or solution file to operate on. If not specified, the command searches the current directory for one. If more than one solution or project is found, an error is thrown.</param>
/// <param name="Framework">Adds project references only when targeting a specific framework using the TFM format.</param>
/// <param name="Diagnostics">Enables diagnostic output.</param>
/// <param name="ShortName">Specifies a short name for this operation.</param>
[Target]
public partial record DotNetAddReference(
    IEnumerable<string> Args,
    IEnumerable<(string name, string value)> Vars,
    IEnumerable<string> References,
    string Project = "",
    string Framework = "",
    bool? Diagnostics = default,
    string ExecutablePath = "",
    string WorkingDirectory = "",
    string ShortName = "")
{
    /// <summary>
    /// Create a new instance of the command.
    /// </summary>
    /// <param name="args">Specifies the set of command line arguments to use when starting the tool.</param>
    public DotNetAddReference(params string[] args)
        : this(args, [], [])
    {
    }

    /// <summary>
    /// Create a new instance of the command.
    /// </summary>
    public DotNetAddReference()
        : this([], [], [])
    {
    }

    /// <inheritdoc/>
    public IStartInfo GetStartInfo(IHost host)
    {
        if (host == null) throw new ArgumentNullException(nameof(host));
        return host.CreateCommandLine(ExecutablePath)
            .WithShortName(ToString())
            .WithWorkingDirectory(WorkingDirectory)
            .WithVars(Vars.ToArray())
            .AddArgs("add")
            .AddNotEmptyArgs(Project)
            .AddArgs("reference")
            .AddNotEmptyArgs(References.ToArray())
            .AddArgs(References.ToArgs("--source"))
            .AddArgs(Framework.ToArgs("--framework"))
            .AddBooleanArgs(
                ("--diagnostics", Diagnostics)
            )
            .AddArgs(Args.ToArray());
    }

    /// <inheritdoc/>
    public override string ToString() => "".GetShortName(ShortName, new [] {"add", Project, "reference"}.Concat(References).ToArray());
}

/// <summary>
/// The dotnet list reference command provides a convenient option to list project references for a given project.
/// </summary>
/// <param name="Args">Specifies the set of command line arguments to use when starting the tool.</param>
/// <param name="Vars">Specifies the set of environment variables that apply to this process and its child processes.</param>
/// <param name="ExecutablePath">Overrides the tool executable path.</param>
/// <param name="WorkingDirectory">Specifies the working directory for the tool to be started.</param>
/// <param name="Project">The project or solution file to operate on. If not specified, the command searches the current directory for one. If more than one solution or project is found, an error is thrown.</param>
/// <param name="Diagnostics">Enables diagnostic output.</param>
/// <param name="ShortName">Specifies a short name for this operation.</param>
[Target]
public partial record DotNetListReference(
    IEnumerable<string> Args,
    IEnumerable<(string name, string value)> Vars,
    string Project = "",
    bool? Diagnostics = default,
    string ExecutablePath = "",
    string WorkingDirectory = "",
    string ShortName = "")
{
    /// <summary>
    /// Create a new instance of the command.
    /// </summary>
    /// <param name="args">Specifies the set of command line arguments to use when starting the tool.</param>
    public DotNetListReference(params string[] args)
        : this(args, [])
    {
    }

    /// <summary>
    /// Create a new instance of the command.
    /// </summary>
    public DotNetListReference()
        : this([], [])
    {
    }

    /// <inheritdoc/>
    public IStartInfo GetStartInfo(IHost host)
    {
        if (host == null) throw new ArgumentNullException(nameof(host));
        return host.CreateCommandLine(ExecutablePath)
            .WithShortName(ToString())
            .WithWorkingDirectory(WorkingDirectory)
            .WithVars(Vars.ToArray())
            .AddArgs("list")
            .AddNotEmptyArgs(Project)
            .AddBooleanArgs(
                ("--diagnostics", Diagnostics)
            )
            .AddArgs(Args.ToArray());
    }

    /// <inheritdoc/>
    public override string ToString() => "".GetShortName(ShortName, "list", Project);
}

/// <summary>
/// Removes project-to-project (P2P) references.
/// </summary>
/// <param name="Args">Specifies the set of command line arguments to use when starting the tool.</param>
/// <param name="Vars">Specifies the set of environment variables that apply to this process and its child processes.</param>
/// <param name="References">Project-to-project (P2P) references to remove. You can specify one or multiple projects. Glob patterns are supported on Unix/Linux based terminals.</param>
/// <param name="ExecutablePath">Overrides the tool executable path.</param>
/// <param name="WorkingDirectory">Specifies the working directory for the tool to be started.</param>
/// <param name="Project">The project or solution file to operate on. If not specified, the command searches the current directory for one. If more than one solution or project is found, an error is thrown.</param>
/// <param name="Framework">Removes the reference only when targeting a specific framework using the TFM format.</param>
/// <param name="Diagnostics">Enables diagnostic output.</param>
/// <param name="ShortName">Specifies a short name for this operation.</param>
[Target]
public partial record DotNetRemoveReference(
    IEnumerable<string> Args,
    IEnumerable<(string name, string value)> Vars,
    IEnumerable<string> References,
    string Project = "",
    string Framework = "",
    bool? Diagnostics = default,
    string ExecutablePath = "",
    string WorkingDirectory = "",
    string ShortName = "")
{
    /// <summary>
    /// Create a new instance of the command.
    /// </summary>
    /// <param name="args">Specifies the set of command line arguments to use when starting the tool.</param>
    public DotNetRemoveReference(params string[] args)
        : this(args, [], [])
    {
    }

    /// <summary>
    /// Create a new instance of the command.
    /// </summary>
    public DotNetRemoveReference()
        : this([], [], [])
    {
    }

    /// <inheritdoc/>
    public IStartInfo GetStartInfo(IHost host)
    {
        if (host == null) throw new ArgumentNullException(nameof(host));
        return host.CreateCommandLine(ExecutablePath)
            .WithShortName(ToString())
            .WithWorkingDirectory(WorkingDirectory)
            .WithVars(Vars.ToArray())
            .AddArgs("remove")
            .AddNotEmptyArgs(Project)
            .AddArgs("reference")
            .AddNotEmptyArgs(References.ToArray())
            .AddArgs(References.ToArgs("--source"))
            .AddArgs(Framework.ToArgs("--framework"))
            .AddBooleanArgs(
                ("--diagnostics", Diagnostics)
            )
            .AddArgs(Args.ToArray());
    }

    /// <inheritdoc/>
    public override string ToString() => "".GetShortName(ShortName, new [] {"remove", Project, "reference"}.Concat(References).ToArray());
}

/// <summary>
/// The dotnet build command builds the project and its dependencies into a set of binaries. The binaries include the project's code in Intermediate Language (IL) files with a .dll extension. Depending on the project type and settings, other files may be included.
/// <example>
/// <code>
/// var configuration = Props.Get("configuration", "Release");
/// 
/// 
/// new DotNetBuild().WithConfiguration(configuration)
///     .Build().EnsureSuccess();
/// </code>
/// </example>
/// </summary>
/// <param name="Args">Specifies the set of command line arguments to use when starting the tool.</param>
/// <param name="Vars">Specifies the set of environment variables that apply to this process and its child processes.</param>
/// <param name="Sources">The URI of the NuGet package source to use during the restore operation.</param>
/// <param name="ExecutablePath">Overrides the tool executable path.</param>
/// <param name="WorkingDirectory">Specifies the working directory for the tool to be started.</param>
/// <param name="Project">The project or solution file to operate on. If not specified, the command searches the current directory for one. If more than one solution or project is found, an error is thrown.</param>
/// <param name="Arch">Specifies the target architecture. This is a shorthand syntax for setting the Runtime Identifier (RID), where the provided value is combined with the default RID. For example, on a win-x64 machine, specifying --arch x86 sets the RID to win-x86. If you use this option, don&apos;t use the -r|--runtime option. Available since .NET 6 Preview 7.</param>
/// <param name="ArtifactsPath">All build output files from the executed command will go in subfolders under the specified path, separated by project.</param>
/// <param name="Configuration">Defines the build configuration. The default for most projects is Debug, but you can override the build configuration settings in your project.</param>
/// <param name="DisableBuildServers">Forces the command to ignore any persistent build servers. This option provides a consistent way to disable all use of build caching, which forces a build from scratch. A build that doesn't rely on caches is useful when the caches might be corrupted or incorrect for some reason. Available since .NET 7 SDK.</param>
/// <param name="Framework">Builds and runs the app using the specified framework. The framework must be specified in the project file.</param>
/// <param name="Force">Forces all dependencies to be resolved even if the last restore was successful. Specifying this flag is the same as deleting the project.assets.json file.</param>
/// <param name="NoDependencies">When restoring a project with project-to-project (P2P) references, restores the root project and not the references.</param>
/// <param name="NoIncremental">Marks the build as unsafe for incremental build. This flag turns off incremental compilation and forces a clean rebuild of the project's dependency graph.</param>
/// <param name="NoRestore">Adds a package reference without performing a restore preview and compatibility check.</param>
/// <param name="NoLogo">Doesn't display the startup banner or the copyright message.</param>
/// <param name="NoSelfContained">Publishes the application as a framework dependent application. A compatible .NET runtime must be installed on the target machine to run the application. Available since .NET 6 SDK.</param>
/// <param name="Output">Directory in which to place the built binaries. If not specified, the default path is ./bin/&lt;configuration&gt;/&lt;framework&gt;/. For projects with multiple target frameworks (via the TargetFrameworks property), you also need to define --framework when you specify this option.</param>
/// <param name="OS">Specifies the target operating system (OS). This is a shorthand syntax for setting the Runtime Identifier (RID), where the provided value is combined with the default RID. For example, on a win-x64 machine, specifying --os linux sets the RID to linux-x64. If you use this option, don&apos;t use the -r|--runtime option. Available since .NET 6.</param>
/// <param name="Runtime">Specifies the target runtime to restore packages for. For a list of Runtime Identifiers (RIDs), see the RID catalog. -r short option available since .NET Core 3.0 SDK.</param>
/// <param name="SelfContained">Publishes the .NET runtime with the application so the runtime doesn't need to be installed on the target machine. The default is true if a runtime identifier is specified. Available since .NET 6.</param>
/// <param name="TerminalLogger">Specifies whether the terminal logger should be used for the build output.</param>
/// <param name="Verbosity">Sets the verbosity level of the command. Allowed values are <see cref="DotNetVerbosity.Quiet"/>, <see cref="DotNetVerbosity.Minimal"/>, <see cref="DotNetVerbosity.Normal"/>, <see cref="DotNetVerbosity.Detailed"/>, and <see cref="DotNetVerbosity.Diagnostic"/>. The default is <see cref="DotNetVerbosity.Minimal"/>. For more information, see <see cref="DotNetVerbosity"/>.</param>
/// <param name="UseCurrentRuntime">Sets the RuntimeIdentifier to a platform portable RuntimeIdentifier based on the one of your machine. This happens implicitly with properties that require a RuntimeIdentifier, such as SelfContained, PublishAot, PublishSelfContained, PublishSingleFile, and PublishReadyToRun. If the property is set to false, that implicit resolution will no longer occur.</param>
/// <param name="VersionSuffix">Sets the value of the $(VersionSuffix) property to use when building the project. This only works if the $(Version) property isn't set. Then, $(Version) is set to the $(VersionPrefix) combined with the $(VersionSuffix), separated by a dash.</param>
/// <param name="Diagnostics">Enables diagnostic output.</param>
/// <param name="ShortName">Specifies a short name for this operation.</param>
[Target]
public partial record DotNetBuild(
    IEnumerable<string> Args,
    IEnumerable<(string name, string value)> Vars,
    IEnumerable<string> Sources,
    string Project = "",
    string Arch = "",
    string ArtifactsPath = "",
    string Configuration = "",
    bool? DisableBuildServers = default,
    string Framework = "",
    bool? Force = default,
    bool? NoDependencies = default,
    bool? NoIncremental = default,
    bool? NoRestore = default,
    bool? NoLogo = default,
    bool? NoSelfContained = default,
    string Output = "",
    string OS = "",
    string Runtime = "",
    bool? SelfContained = default,
    TerminalLogger? TerminalLogger = default,
    DotNetVerbosity? Verbosity = default,
    bool? UseCurrentRuntime = default,
    string VersionSuffix = "",
    bool? Diagnostics = default,
    string ExecutablePath = "",
    string WorkingDirectory = "",
    string ShortName = "")
{
    /// <summary>
    /// Create a new instance of the command.
    /// </summary>
    /// <param name="args">Specifies the set of command line arguments to use when starting the tool.</param>
    public DotNetBuild(params string[] args)
        : this(args, [], [])
    {
    }

    /// <summary>
    /// Create a new instance of the command.
    /// </summary>
    public DotNetBuild()
        : this([], [], [])
    {
    }

    /// <inheritdoc/>
    public IStartInfo GetStartInfo(IHost host)
    {
        if (host == null) throw new ArgumentNullException(nameof(host));
        return host.CreateCommandLine(ExecutablePath)
            .WithShortName(ToString())
            .WithWorkingDirectory(WorkingDirectory)
            .WithVars(Vars.ToArray())
            .AddArgs("build")
            .AddNotEmptyArgs(Project)
            .AddMSBuildLoggers(host, Verbosity)
            .AddArgs(Sources.ToArgs("--source"))
            .AddArgs(Arch.ToArgs("--arch"))
            .AddArgs(ArtifactsPath.ToArgs("--artifacts-path"))
            .AddArgs(Configuration.ToArgs("--configuration"))
            .AddArgs(Framework.ToArgs("--framework"))
            .AddArgs(Output.ToArgs("--output"))
            .AddArgs(OS.ToArgs("--os"))
            .AddArgs(Runtime.ToArgs("--runtime"))
            .AddArgs(TerminalLogger.ToArgs("--tl"))
            .AddArgs(Verbosity.ToArgs("--verbosity"))
            .AddArgs(VersionSuffix.ToArgs("--version-suffix"))
            .AddBooleanArgs(
                ("--disable-build-servers", DisableBuildServers),
                ("--force", Force),
                ("--no-dependencies", NoDependencies),
                ("--no-incremental", NoIncremental),
                ("--no-restore", NoRestore),
                ("--nologo", NoLogo),
                ("--no-self-contained", NoSelfContained),
                ("--self-contained", SelfContained),
                ("--use-current-runtime", UseCurrentRuntime),
                ("--diagnostics", Diagnostics)
            )
            .AddArgs(Args.ToArray());
    }

    /// <inheritdoc/>
    public override string ToString() => "".GetShortName(ShortName, "build", Project);
}

/// <summary>
/// Shuts down build servers that are started from dotnet. By default, all servers are shut down.
/// </summary>
/// <param name="Args">Specifies the set of command line arguments to use when starting the tool.</param>
/// <param name="Vars">Specifies the set of environment variables that apply to this process and its child processes.</param>
/// <param name="Servers">Shuts down build servers that are started from dotnet. By default, all servers are shut down.</param>
/// <param name="ExecutablePath">Overrides the tool executable path.</param>
/// <param name="WorkingDirectory">Specifies the working directory for the tool to be started.</param>
/// <param name="Diagnostics">Enables diagnostic output.</param>
/// <param name="ShortName">Specifies a short name for this operation.</param>
[Target]
public partial record DotNetBuildServerShutdown(
    IEnumerable<string> Args,
    IEnumerable<(string name, string value)> Vars,
    IEnumerable<DotNetBuildServer> Servers,
    bool? Diagnostics = default,
    string ExecutablePath = "",
    string WorkingDirectory = "",
    string ShortName = "")
{
    /// <summary>
    /// Create a new instance of the command.
    /// </summary>
    /// <param name="args">Specifies the set of command line arguments to use when starting the tool.</param>
    public DotNetBuildServerShutdown(params string[] args)
        : this(args, [], [])
    {
    }

    /// <summary>
    /// Create a new instance of the command.
    /// </summary>
    public DotNetBuildServerShutdown()
        : this([], [], [])
    {
    }

    /// <inheritdoc/>
    public IStartInfo GetStartInfo(IHost host)
    {
        if (host == null) throw new ArgumentNullException(nameof(host));
        return host.CreateCommandLine(ExecutablePath)
            .WithShortName(ToString())
            .WithWorkingDirectory(WorkingDirectory)
            .WithVars(Vars.ToArray())
            .AddArgs("build-server")
            .AddArgs("shutdown")
            .AddArgs(Servers.ToArgs(""))
            .AddBooleanArgs(
                ("--diagnostics", Diagnostics)
            )
            .AddArgs(Args.ToArray());
    }

    /// <inheritdoc/>
    public override string ToString() => "".GetShortName(ShortName, "build-server", "shutdown");
}

/// <summary>
/// Cleans the output of the previous build. It's implemented as an MSBuild target, so the project is evaluated when the command is run. Only the outputs created during the build are cleaned. Both intermediate (obj) and final output (bin) folders are cleaned.
/// </summary>
/// <param name="Args">Specifies the set of command line arguments to use when starting the tool.</param>
/// <param name="Vars">Specifies the set of environment variables that apply to this process and its child processes.</param>
/// <param name="Props">MSBuild options for setting properties.</param>
/// <param name="ExecutablePath">Overrides the tool executable path.</param>
/// <param name="WorkingDirectory">Specifies the working directory for the tool to be started.</param>
/// <param name="Project">The project or solution file to operate on. If not specified, the command searches the current directory for one. If more than one solution or project is found, an error is thrown.</param>
/// <param name="ArtifactsPath">All build output files from the executed command will go in subfolders under the specified path, separated by project.</param>
/// <param name="Configuration">Defines the build configuration. The default for most projects is Debug, but you can override the build configuration settings in your project.</param>
/// <param name="Framework">Builds and runs the app using the specified framework. The framework must be specified in the project file.</param>
/// <param name="NoLogo">Doesn't display the startup banner or the copyright message.</param>
/// <param name="Output">Directory in which to place the built binaries. If not specified, the default path is ./bin/&lt;configuration&gt;/&lt;framework&gt;/. For projects with multiple target frameworks (via the TargetFrameworks property), you also need to define --framework when you specify this option.</param>
/// <param name="Runtime">Specifies the target runtime to restore packages for. For a list of Runtime Identifiers (RIDs), see the RID catalog. -r short option available since .NET Core 3.0 SDK.</param>
/// <param name="TerminalLogger">Specifies whether the terminal logger should be used for the build output.</param>
/// <param name="Verbosity">Sets the verbosity level of the command. Allowed values are <see cref="DotNetVerbosity.Quiet"/>, <see cref="DotNetVerbosity.Minimal"/>, <see cref="DotNetVerbosity.Normal"/>, <see cref="DotNetVerbosity.Detailed"/>, and <see cref="DotNetVerbosity.Diagnostic"/>. The default is <see cref="DotNetVerbosity.Minimal"/>. For more information, see <see cref="DotNetVerbosity"/>.</param>
/// <param name="Diagnostics">Enables diagnostic output.</param>
/// <param name="ShortName">Specifies a short name for this operation.</param>
[Target]
public partial record DotNetClean(
    IEnumerable<string> Args,
    IEnumerable<(string name, string value)> Vars,
    IEnumerable<(string name, string value)> Props,
    string Project = "",
    string ArtifactsPath = "",
    string Configuration = "",
    string Framework = "",
    bool? NoLogo = default,
    string Output = "",
    string Runtime = "",
    TerminalLogger? TerminalLogger = default,
    DotNetVerbosity? Verbosity = default,
    bool? Diagnostics = default,
    string ExecutablePath = "",
    string WorkingDirectory = "",
    string ShortName = "")
{
    /// <summary>
    /// Create a new instance of the command.
    /// </summary>
    /// <param name="args">Specifies the set of command line arguments to use when starting the tool.</param>
    public DotNetClean(params string[] args)
        : this(args, [], [])
    {
    }

    /// <summary>
    /// Create a new instance of the command.
    /// </summary>
    public DotNetClean()
        : this([], [], [])
    {
    }

    /// <inheritdoc/>
    public IStartInfo GetStartInfo(IHost host)
    {
        if (host == null) throw new ArgumentNullException(nameof(host));
        return host.CreateCommandLine(ExecutablePath)
            .WithShortName(ToString())
            .WithWorkingDirectory(WorkingDirectory)
            .WithVars(Vars.ToArray())
            .AddArgs("clean")
            .AddNotEmptyArgs(Project)
            .AddMSBuildLoggers(host, Verbosity)
            .AddArgs(ArtifactsPath.ToArgs("--artifacts-path"))
            .AddArgs(Configuration.ToArgs("--configuration"))
            .AddArgs(Framework.ToArgs("--framework"))
            .AddArgs(Output.ToArgs("--output"))
            .AddArgs(Runtime.ToArgs("--runtime"))
            .AddArgs(TerminalLogger.ToArgs("--tl"))
            .AddArgs(Verbosity.ToArgs("--verbosity"))
            .AddBooleanArgs(
                ("--nologo", NoLogo),
                ("--diagnostics", Diagnostics)
            )
            .AddProps("--property", Props.ToArray())
            .AddArgs(Args.ToArray());
    }

    /// <inheritdoc/>
    public override string ToString() => "".GetShortName(ShortName, "clean", Project);
}

/// <summary>
/// Generates a self-signed certificate to enable HTTPS use in development. The dotnet dev-certs command manages a self-signed certificate to enable HTTPS use in local web app development. The dotnet dev-certs https command with no options checks if a development certificate is present in the current user's certificate store on the machine.
/// </summary>
/// <param name="Args">Specifies the set of command line arguments to use when starting the tool.</param>
/// <param name="Vars">Specifies the set of environment variables that apply to this process and its child processes.</param>
/// <param name="ExecutablePath">Overrides the tool executable path.</param>
/// <param name="WorkingDirectory">Specifies the working directory for the tool to be started.</param>
/// <param name="Check">Checks for the existence of the development certificate but doesn't perform any action. Use this option with the --trust option to check if the certificate is not only valid but also trusted.</param>
/// <param name="Clean">Removes all HTTPS development certificates from the certificate store by using the .NET certificate store API. Doesn't remove any physical files that were created by using the --export-path option. On macOS in .NET 7.0, the dotnet dev-certs command creates the certificate on a path on disk, and the clean operation removes that certificate file.</param>
/// <param name="ExportPath">Exports the certificate to a file so that it can be used by other tools. Specify the full path to the exported certificate file, including the file name.</param>
/// <param name="Format">When used with --export-path, specifies the format of the exported certificate file. Valid values are PFX and PEM, case-insensitive. PFX is the default. The file format is independent of the file name extension. For example, if you specify --format pfx and --export-path ./cert.pem, you'll get a file named cert.pem in PFX format.</param>
/// <param name="Import">Imports the provided HTTPS development certificate into the local machine. Requires that you also specify the --clean option, which clears out any existing HTTPS developer certificates.</param>
/// <param name="NoPassword">Doesn't use a password for the key when exporting a certificate to PEM format files. The key file is exported in plain text. This option is not applicable to PFX files and is intended for internal testing use only.</param>
/// <param name="Password">Specifies the password to use.</param>
/// <param name="Quiet">Display warnings and errors only.</param>
/// <param name="Trust">rusts the certificate on the local machine. If this option isn't specified, the certificate is added to the certificate store but not to a trusted list. When combined with the --check option, validates that the certificate is trusted.</param>
/// <param name="Verbose">Display debug information.</param>
/// <param name="Diagnostics">Enables diagnostic output.</param>
/// <param name="ShortName">Specifies a short name for this operation.</param>
[Target]
public partial record DotNetDevCertsHttps(
    IEnumerable<string> Args,
    IEnumerable<(string name, string value)> Vars,
    bool? Check = default,
    bool? Clean = default,
    string ExportPath = "",
    string Format = "",
    string Import = "",
    bool? NoPassword = default,
    bool? Password = default,
    bool? Quiet = default,
    bool? Trust = default,
    bool? Verbose = default,
    bool? Diagnostics = default,
    string ExecutablePath = "",
    string WorkingDirectory = "",
    string ShortName = "")
{
    /// <summary>
    /// Create a new instance of the command.
    /// </summary>
    /// <param name="args">Specifies the set of command line arguments to use when starting the tool.</param>
    public DotNetDevCertsHttps(params string[] args)
        : this(args, [])
    {
    }

    /// <summary>
    /// Create a new instance of the command.
    /// </summary>
    public DotNetDevCertsHttps()
        : this([], [])
    {
    }

    /// <inheritdoc/>
    public IStartInfo GetStartInfo(IHost host)
    {
        if (host == null) throw new ArgumentNullException(nameof(host));
        return host.CreateCommandLine(ExecutablePath)
            .WithShortName(ToString())
            .WithWorkingDirectory(WorkingDirectory)
            .WithVars(Vars.ToArray())
            .AddArgs("dev-certs")
            .AddArgs("https")
            .AddArgs(ExportPath.ToArgs("--export-path"))
            .AddArgs(Format.ToArgs("--format"))
            .AddArgs(Import.ToArgs("--import"))
            .AddBooleanArgs(
                ("--check", Check),
                ("--clean", Clean),
                ("--no-password", NoPassword),
                ("--password", Password),
                ("--quiet", Quiet),
                ("--trust", Trust),
                ("--verbose", Verbose),
                ("--diagnostics", Diagnostics)
            )
            .AddArgs(Args.ToArray());
    }

    /// <inheritdoc/>
    public override string ToString() => "".GetShortName(ShortName, "dev-certs", "https");
}

/// <summary>
/// Formats code to match editorconfig settings.
/// </summary>
/// <param name="Args">Specifies the set of command line arguments to use when starting the tool.</param>
/// <param name="Vars">Specifies the set of environment variables that apply to this process and its child processes.</param>
/// <param name="ExecutablePath">Overrides the tool executable path.</param>
/// <param name="WorkingDirectory">Specifies the working directory for the tool to be started.</param>
/// <param name="Project">The project or solution file to operate on. If not specified, the command searches the current directory for one. If more than one solution or project is found, an error is thrown.</param>
/// <param name="Diagnostics">A space-separated list of diagnostic IDs to use as a filter when fixing code style or third-party issues. Default value is whichever IDs are listed in the .editorconfig file. For a list of built-in analyzer rule IDs that you can specify, see the list of IDs for code-analysis style rules.</param>
/// <param name="Severity">The minimum severity of diagnostics to fix. Allowed values are info, warn, and error. The default value is warn</param>
/// <param name="NoRestore">Doesn't execute an implicit restore before formatting. Default is to do implicit restore.</param>
/// <param name="VerifyNoChanges">Verifies that no formatting changes would be performed. Terminates with a non zero exit code if any files would have been formatted.</param>
/// <param name="Include">A space-separated list of relative file or folder paths to include in formatting. The default is all files in the solution or project.</param>
/// <param name="Exclude">A space-separated list of relative file or folder paths to exclude from formatting. The default is none.</param>
/// <param name="IncludeGenerated">Formats files generated by the SDK.</param>
/// <param name="Verbosity">Sets the verbosity level of the command. Allowed values are <see cref="DotNetVerbosity.Quiet"/>, <see cref="DotNetVerbosity.Minimal"/>, <see cref="DotNetVerbosity.Normal"/>, <see cref="DotNetVerbosity.Detailed"/>, and <see cref="DotNetVerbosity.Diagnostic"/>. The default is <see cref="DotNetVerbosity.Minimal"/>. For more information, see <see cref="DotNetVerbosity"/>.</param>
/// <param name="BinaryLog">Logs all project or solution load information to a binary log file.</param>
/// <param name="Report">Logs all project or solution load information to a binary log file.</param>
/// <param name="ShortName">Specifies a short name for this operation.</param>
[Target]
public partial record DotNetFormat(
    IEnumerable<string> Args,
    IEnumerable<(string name, string value)> Vars,
    string Project = "",
    string Diagnostics = "",
    DotnetFormatSeverity? Severity = default,
    bool? NoRestore = default,
    bool? VerifyNoChanges = default,
    string Include = "",
    string Exclude = "",
    bool? IncludeGenerated = default,
    DotNetVerbosity? Verbosity = default,
    string BinaryLog = "",
    string Report = "",
    string ExecutablePath = "",
    string WorkingDirectory = "",
    string ShortName = "")
{
    /// <summary>
    /// Create a new instance of the command.
    /// </summary>
    /// <param name="args">Specifies the set of command line arguments to use when starting the tool.</param>
    public DotNetFormat(params string[] args)
        : this(args, [])
    {
    }

    /// <summary>
    /// Create a new instance of the command.
    /// </summary>
    public DotNetFormat()
        : this([], [])
    {
    }

    /// <inheritdoc/>
    public IStartInfo GetStartInfo(IHost host)
    {
        if (host == null) throw new ArgumentNullException(nameof(host));
        return host.CreateCommandLine(ExecutablePath)
            .WithShortName(ToString())
            .WithWorkingDirectory(WorkingDirectory)
            .WithVars(Vars.ToArray())
            .AddArgs("format")
            .AddNotEmptyArgs(Project)
            .AddArgs(Diagnostics.ToArgs("--diagnostics"))
            .AddArgs(Severity.ToArgs("--severity"))
            .AddArgs(Include.ToArgs("--include"))
            .AddArgs(Exclude.ToArgs("--exclude"))
            .AddArgs(Verbosity.ToArgs("--verbosity"))
            .AddArgs(BinaryLog.ToArgs("--binarylog"))
            .AddArgs(Report.ToArgs("--report"))
            .AddBooleanArgs(
                ("--no-restore", NoRestore),
                ("--verify-no-changes", VerifyNoChanges),
                ("--include-generated", IncludeGenerated)
            )
            .AddArgs(Args.ToArray());
    }

    /// <inheritdoc/>
    public override string ToString() => "".GetShortName(ShortName, "format", Project);
}

/// <summary>
/// Formats code to match editorconfig settings for whitespace. The dotnet format whitespace subcommand only runs formatting rules associated with whitespace formatting.
/// </summary>
/// <param name="Args">Specifies the set of command line arguments to use when starting the tool.</param>
/// <param name="Vars">Specifies the set of environment variables that apply to this process and its child processes.</param>
/// <param name="ExecutablePath">Overrides the tool executable path.</param>
/// <param name="WorkingDirectory">Specifies the working directory for the tool to be started.</param>
/// <param name="Project">The project or solution file to operate on. If not specified, the command searches the current directory for one. If more than one solution or project is found, an error is thrown.</param>
/// <param name="Diagnostics">A space-separated list of diagnostic IDs to use as a filter when fixing code style or third-party issues. Default value is whichever IDs are listed in the .editorconfig file. For a list of built-in analyzer rule IDs that you can specify, see the list of IDs for code-analysis style rules.</param>
/// <param name="Severity">The minimum severity of diagnostics to fix. Allowed values are info, warn, and error. The default value is warn</param>
/// <param name="NoRestore">Doesn't execute an implicit restore before formatting. Default is to do implicit restore.</param>
/// <param name="VerifyNoChanges">Verifies that no formatting changes would be performed. Terminates with a non zero exit code if any files would have been formatted.</param>
/// <param name="Include">A space-separated list of relative file or folder paths to include in formatting. The default is all files in the solution or project.</param>
/// <param name="Exclude">A space-separated list of relative file or folder paths to exclude from formatting. The default is none.</param>
/// <param name="IncludeGenerated">Formats files generated by the SDK.</param>
/// <param name="Verbosity">Sets the verbosity level of the command. Allowed values are <see cref="DotNetVerbosity.Quiet"/>, <see cref="DotNetVerbosity.Minimal"/>, <see cref="DotNetVerbosity.Normal"/>, <see cref="DotNetVerbosity.Detailed"/>, and <see cref="DotNetVerbosity.Diagnostic"/>. The default is <see cref="DotNetVerbosity.Minimal"/>. For more information, see <see cref="DotNetVerbosity"/>.</param>
/// <param name="BinaryLog">Logs all project or solution load information to a binary log file.</param>
/// <param name="Report">Logs all project or solution load information to a binary log file.</param>
/// <param name="Folder">Treat the project (or solution) argument as a path to a simple folder of code files.</param>
/// <param name="ShortName">Specifies a short name for this operation.</param>
[Target]
public partial record DotNetFormatWhitespace(
    IEnumerable<string> Args,
    IEnumerable<(string name, string value)> Vars,
    string Project = "",
    string Diagnostics = "",
    DotnetFormatSeverity? Severity = default,
    bool? NoRestore = default,
    bool? VerifyNoChanges = default,
    string Include = "",
    string Exclude = "",
    bool? IncludeGenerated = default,
    DotNetVerbosity? Verbosity = default,
    string BinaryLog = "",
    string Report = "",
    bool? Folder = default,
    string ExecutablePath = "",
    string WorkingDirectory = "",
    string ShortName = "")
{
    /// <summary>
    /// Create a new instance of the command.
    /// </summary>
    /// <param name="args">Specifies the set of command line arguments to use when starting the tool.</param>
    public DotNetFormatWhitespace(params string[] args)
        : this(args, [])
    {
    }

    /// <summary>
    /// Create a new instance of the command.
    /// </summary>
    public DotNetFormatWhitespace()
        : this([], [])
    {
    }

    /// <inheritdoc/>
    public IStartInfo GetStartInfo(IHost host)
    {
        if (host == null) throw new ArgumentNullException(nameof(host));
        return host.CreateCommandLine(ExecutablePath)
            .WithShortName(ToString())
            .WithWorkingDirectory(WorkingDirectory)
            .WithVars(Vars.ToArray())
            .AddArgs("format")
            .AddNotEmptyArgs(Project)
            .AddArgs("whitespace")
            .AddArgs(Diagnostics.ToArgs("--diagnostics"))
            .AddArgs(Severity.ToArgs("--severity"))
            .AddArgs(Include.ToArgs("--include"))
            .AddArgs(Exclude.ToArgs("--exclude"))
            .AddArgs(Verbosity.ToArgs("--verbosity"))
            .AddArgs(BinaryLog.ToArgs("--binarylog"))
            .AddArgs(Report.ToArgs("--report"))
            .AddBooleanArgs(
                ("--no-restore", NoRestore),
                ("--verify-no-changes", VerifyNoChanges),
                ("--include-generated", IncludeGenerated),
                ("--folder", Folder)
            )
            .AddArgs(Args.ToArray());
    }

    /// <inheritdoc/>
    public override string ToString() => "".GetShortName(ShortName, "format", Project, "whitespace");
}

/// <summary>
/// Formats code to match EditorConfig settings for code style. The dotnet format style subcommand only runs formatting rules associated with code style formatting.
/// </summary>
/// <param name="Args">Specifies the set of command line arguments to use when starting the tool.</param>
/// <param name="Vars">Specifies the set of environment variables that apply to this process and its child processes.</param>
/// <param name="ExecutablePath">Overrides the tool executable path.</param>
/// <param name="WorkingDirectory">Specifies the working directory for the tool to be started.</param>
/// <param name="Project">The project or solution file to operate on. If not specified, the command searches the current directory for one. If more than one solution or project is found, an error is thrown.</param>
/// <param name="Diagnostics">A space-separated list of diagnostic IDs to use as a filter when fixing code style or third-party issues. Default value is whichever IDs are listed in the .editorconfig file. For a list of built-in analyzer rule IDs that you can specify, see the list of IDs for code-analysis style rules.</param>
/// <param name="Severity">The minimum severity of diagnostics to fix. Allowed values are info, warn, and error. The default value is warn</param>
/// <param name="NoRestore">Doesn't execute an implicit restore before formatting. Default is to do implicit restore.</param>
/// <param name="VerifyNoChanges">Verifies that no formatting changes would be performed. Terminates with a non zero exit code if any files would have been formatted.</param>
/// <param name="Include">A space-separated list of relative file or folder paths to include in formatting. The default is all files in the solution or project.</param>
/// <param name="Exclude">A space-separated list of relative file or folder paths to exclude from formatting. The default is none.</param>
/// <param name="IncludeGenerated">Formats files generated by the SDK.</param>
/// <param name="Verbosity">Sets the verbosity level of the command. Allowed values are <see cref="DotNetVerbosity.Quiet"/>, <see cref="DotNetVerbosity.Minimal"/>, <see cref="DotNetVerbosity.Normal"/>, <see cref="DotNetVerbosity.Detailed"/>, and <see cref="DotNetVerbosity.Diagnostic"/>. The default is <see cref="DotNetVerbosity.Minimal"/>. For more information, see <see cref="DotNetVerbosity"/>.</param>
/// <param name="BinaryLog">Logs all project or solution load information to a binary log file.</param>
/// <param name="Report">Logs all project or solution load information to a binary log file.</param>
/// <param name="ShortName">Specifies a short name for this operation.</param>
[Target]
public partial record DotNetFormatStyle(
    IEnumerable<string> Args,
    IEnumerable<(string name, string value)> Vars,
    string Project = "",
    string Diagnostics = "",
    DotnetFormatSeverity? Severity = default,
    bool? NoRestore = default,
    bool? VerifyNoChanges = default,
    string Include = "",
    string Exclude = "",
    bool? IncludeGenerated = default,
    DotNetVerbosity? Verbosity = default,
    string BinaryLog = "",
    string Report = "",
    string ExecutablePath = "",
    string WorkingDirectory = "",
    string ShortName = "")
{
    /// <summary>
    /// Create a new instance of the command.
    /// </summary>
    /// <param name="args">Specifies the set of command line arguments to use when starting the tool.</param>
    public DotNetFormatStyle(params string[] args)
        : this(args, [])
    {
    }

    /// <summary>
    /// Create a new instance of the command.
    /// </summary>
    public DotNetFormatStyle()
        : this([], [])
    {
    }

    /// <inheritdoc/>
    public IStartInfo GetStartInfo(IHost host)
    {
        if (host == null) throw new ArgumentNullException(nameof(host));
        return host.CreateCommandLine(ExecutablePath)
            .WithShortName(ToString())
            .WithWorkingDirectory(WorkingDirectory)
            .WithVars(Vars.ToArray())
            .AddArgs("format")
            .AddNotEmptyArgs(Project)
            .AddArgs("style")
            .AddArgs(Diagnostics.ToArgs("--diagnostics"))
            .AddArgs(Severity.ToArgs("--severity"))
            .AddArgs(Include.ToArgs("--include"))
            .AddArgs(Exclude.ToArgs("--exclude"))
            .AddArgs(Verbosity.ToArgs("--verbosity"))
            .AddArgs(BinaryLog.ToArgs("--binarylog"))
            .AddArgs(Report.ToArgs("--report"))
            .AddBooleanArgs(
                ("--no-restore", NoRestore),
                ("--verify-no-changes", VerifyNoChanges),
                ("--include-generated", IncludeGenerated)
            )
            .AddArgs(Args.ToArray());
    }

    /// <inheritdoc/>
    public override string ToString() => "".GetShortName(ShortName, "format", Project, "style");
}

/// <summary>
/// Formats code to match editorconfig settings for analyzers (excluding code style rules). The dotnet format analyzers subcommand only runs formatting rules associated with analyzers.
/// </summary>
/// <param name="Args">Specifies the set of command line arguments to use when starting the tool.</param>
/// <param name="Vars">Specifies the set of environment variables that apply to this process and its child processes.</param>
/// <param name="ExecutablePath">Overrides the tool executable path.</param>
/// <param name="WorkingDirectory">Specifies the working directory for the tool to be started.</param>
/// <param name="Project">The project or solution file to operate on. If not specified, the command searches the current directory for one. If more than one solution or project is found, an error is thrown.</param>
/// <param name="Diagnostics">A space-separated list of diagnostic IDs to use as a filter when fixing code style or third-party issues. Default value is whichever IDs are listed in the .editorconfig file. For a list of built-in analyzer rule IDs that you can specify, see the list of IDs for code-analysis style rules.</param>
/// <param name="Severity">The minimum severity of diagnostics to fix. Allowed values are info, warn, and error. The default value is warn</param>
/// <param name="NoRestore">Doesn't execute an implicit restore before formatting. Default is to do implicit restore.</param>
/// <param name="VerifyNoChanges">Verifies that no formatting changes would be performed. Terminates with a non zero exit code if any files would have been formatted.</param>
/// <param name="Include">A space-separated list of relative file or folder paths to include in formatting. The default is all files in the solution or project.</param>
/// <param name="Exclude">A space-separated list of relative file or folder paths to exclude from formatting. The default is none.</param>
/// <param name="IncludeGenerated">Formats files generated by the SDK.</param>
/// <param name="Verbosity">Sets the verbosity level of the command. Allowed values are <see cref="DotNetVerbosity.Quiet"/>, <see cref="DotNetVerbosity.Minimal"/>, <see cref="DotNetVerbosity.Normal"/>, <see cref="DotNetVerbosity.Detailed"/>, and <see cref="DotNetVerbosity.Diagnostic"/>. The default is <see cref="DotNetVerbosity.Minimal"/>. For more information, see <see cref="DotNetVerbosity"/>.</param>
/// <param name="BinaryLog">Logs all project or solution load information to a binary log file.</param>
/// <param name="Report">Logs all project or solution load information to a binary log file.</param>
/// <param name="ShortName">Specifies a short name for this operation.</param>
[Target]
public partial record DotNetFormatAnalyzers(
    IEnumerable<string> Args,
    IEnumerable<(string name, string value)> Vars,
    string Project = "",
    string Diagnostics = "",
    DotnetFormatSeverity? Severity = default,
    bool? NoRestore = default,
    bool? VerifyNoChanges = default,
    string Include = "",
    string Exclude = "",
    bool? IncludeGenerated = default,
    DotNetVerbosity? Verbosity = default,
    string BinaryLog = "",
    string Report = "",
    string ExecutablePath = "",
    string WorkingDirectory = "",
    string ShortName = "")
{
    /// <summary>
    /// Create a new instance of the command.
    /// </summary>
    /// <param name="args">Specifies the set of command line arguments to use when starting the tool.</param>
    public DotNetFormatAnalyzers(params string[] args)
        : this(args, [])
    {
    }

    /// <summary>
    /// Create a new instance of the command.
    /// </summary>
    public DotNetFormatAnalyzers()
        : this([], [])
    {
    }

    /// <inheritdoc/>
    public IStartInfo GetStartInfo(IHost host)
    {
        if (host == null) throw new ArgumentNullException(nameof(host));
        return host.CreateCommandLine(ExecutablePath)
            .WithShortName(ToString())
            .WithWorkingDirectory(WorkingDirectory)
            .WithVars(Vars.ToArray())
            .AddArgs("format")
            .AddNotEmptyArgs(Project)
            .AddArgs("analyzers")
            .AddArgs(Diagnostics.ToArgs("--diagnostics"))
            .AddArgs(Severity.ToArgs("--severity"))
            .AddArgs(Include.ToArgs("--include"))
            .AddArgs(Exclude.ToArgs("--exclude"))
            .AddArgs(Verbosity.ToArgs("--verbosity"))
            .AddArgs(BinaryLog.ToArgs("--binarylog"))
            .AddArgs(Report.ToArgs("--report"))
            .AddBooleanArgs(
                ("--no-restore", NoRestore),
                ("--verify-no-changes", VerifyNoChanges),
                ("--include-generated", IncludeGenerated)
            )
            .AddArgs(Args.ToArray());
    }

    /// <inheritdoc/>
    public override string ToString() => "".GetShortName(ShortName, "format", Project, "analyzers");
}

/// <summary>
/// Runs source code without any explicit compile or launch commands.
/// <example>
/// <code>
/// var result = new DotNetNew("console", "-n", "MyApp", "--force")
///     .Build().EnsureSuccess();
/// 
/// 
/// new DotNetRun().WithWorkingDirectory("MyApp")
///     .Build().EnsureSuccess();
/// </code>
/// </example>
/// </summary>
/// <param name="Args">Specifies the set of command line arguments to use when starting the tool.</param>
/// <param name="Vars">Specifies the set of environment variables that apply to this process and its child processes.</param>
/// <param name="Props">MSBuild options for setting properties.</param>
/// <param name="ExecutablePath">Overrides the tool executable path.</param>
/// <param name="WorkingDirectory">Specifies the working directory for the tool to be started.</param>
/// <param name="Project">The project or solution file to operate on. If not specified, the command searches the current directory for one. If more than one solution or project is found, an error is thrown.</param>
/// <param name="Arch">Specifies the target architecture. This is a shorthand syntax for setting the Runtime Identifier (RID), where the provided value is combined with the default RID. For example, on a win-x64 machine, specifying --arch x86 sets the RID to win-x86. If you use this option, don&apos;t use the -r|--runtime option. Available since .NET 6 Preview 7.</param>
/// <param name="Configuration">Defines the build configuration. The default for most projects is Debug, but you can override the build configuration settings in your project.</param>
/// <param name="Framework">Builds and runs the app using the specified framework. The framework must be specified in the project file.</param>
/// <param name="Force">Forces all dependencies to be resolved even if the last restore was successful. Specifying this flag is the same as deleting the project.assets.json file.</param>
/// <param name="LaunchProfile">The name of the launch profile (if any) to use when launching the application. Launch profiles are defined in the launchSettings.json file and are typically called Development, Staging, and Production.</param>
/// <param name="NoBuild">Doesn't build the project before running. It also implicit sets the --no-restore flag.</param>
/// <param name="NoDependencies">When restoring a project with project-to-project (P2P) references, restores the root project and not the references.</param>
/// <param name="NoLaunchProfile">Doesn't try to use launchSettings.json to configure the application.</param>
/// <param name="NoRestore">Adds a package reference without performing a restore preview and compatibility check.</param>
/// <param name="OS">Specifies the target operating system (OS). This is a shorthand syntax for setting the Runtime Identifier (RID), where the provided value is combined with the default RID. For example, on a win-x64 machine, specifying --os linux sets the RID to linux-x64. If you use this option, don&apos;t use the -r|--runtime option. Available since .NET 6.</param>
/// <param name="Runtime">Specifies the target runtime to restore packages for. For a list of Runtime Identifiers (RIDs), see the RID catalog. -r short option available since .NET Core 3.0 SDK.</param>
/// <param name="TerminalLogger">Specifies whether the terminal logger should be used for the build output.</param>
/// <param name="Verbosity">Sets the verbosity level of the command. Allowed values are <see cref="DotNetVerbosity.Quiet"/>, <see cref="DotNetVerbosity.Minimal"/>, <see cref="DotNetVerbosity.Normal"/>, <see cref="DotNetVerbosity.Detailed"/>, and <see cref="DotNetVerbosity.Diagnostic"/>. The default is <see cref="DotNetVerbosity.Minimal"/>. For more information, see <see cref="DotNetVerbosity"/>.</param>
/// <param name="Diagnostics">Enables diagnostic output.</param>
/// <param name="ShortName">Specifies a short name for this operation.</param>
[Target]
public partial record DotNetRun(
    IEnumerable<string> Args,
    IEnumerable<(string name, string value)> Vars,
    IEnumerable<(string name, string value)> Props,
    string Project = "",
    string Arch = "",
    string Configuration = "",
    string Framework = "",
    bool? Force = default,
    string LaunchProfile = "",
    bool? NoBuild = default,
    bool? NoDependencies = default,
    bool? NoLaunchProfile = default,
    bool? NoRestore = default,
    string OS = "",
    string Runtime = "",
    TerminalLogger? TerminalLogger = default,
    DotNetVerbosity? Verbosity = default,
    bool? Diagnostics = default,
    string ExecutablePath = "",
    string WorkingDirectory = "",
    string ShortName = "")
{
    /// <summary>
    /// Create a new instance of the command.
    /// </summary>
    /// <param name="args">Specifies the set of command line arguments to use when starting the tool.</param>
    public DotNetRun(params string[] args)
        : this(args, [], [])
    {
    }

    /// <summary>
    /// Create a new instance of the command.
    /// </summary>
    public DotNetRun()
        : this([], [], [])
    {
    }

    /// <inheritdoc/>
    public IStartInfo GetStartInfo(IHost host)
    {
        if (host == null) throw new ArgumentNullException(nameof(host));
        return host.CreateCommandLine(ExecutablePath)
            .WithShortName(ToString())
            .WithWorkingDirectory(WorkingDirectory)
            .WithVars(Vars.ToArray())
            .AddArgs("run")
            .AddNotEmptyArgs(Project)
            .AddArgs(Arch.ToArgs("--arch"))
            .AddArgs(Configuration.ToArgs("--configuration"))
            .AddArgs(Framework.ToArgs("--framework"))
            .AddArgs(LaunchProfile.ToArgs("--launch-profile"))
            .AddArgs(OS.ToArgs("--os"))
            .AddArgs(Runtime.ToArgs("--runtime"))
            .AddArgs(TerminalLogger.ToArgs("--tl"))
            .AddArgs(Verbosity.ToArgs("--verbosity"))
            .AddBooleanArgs(
                ("--force", Force),
                ("--no-build", NoBuild),
                ("--no-dependencies", NoDependencies),
                ("--no-launch-profile", NoLaunchProfile),
                ("--no-restore", NoRestore),
                ("--diagnostics", Diagnostics)
            )
            .AddProps("--property", Props.ToArray())
            .AddArgs(Args.ToArray());
    }

    /// <inheritdoc/>
    public override string ToString() => "".GetShortName(ShortName, "run", Project);
}

